spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=backend

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=JtjlHhSAIAamhDeMHADfAPCynpCNCqHE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraci\u00f3n para subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB