spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=backend

spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:50262/railway
spring.datasource.username=root
spring.datasource.password=aHMdmuimHVxrbasMUipSdKwTMVjYcsgR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true